// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chat: typeof import('./components/chat/Chat.vue')['default']
    ChatContent: typeof import('./components/chat/ChatContent.vue')['default']
    ChatMessage: typeof import('./components/chat/ChatMessage.vue')['default']
    GroupList: typeof import('./components/GroupList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}
